
name: "generate-snake-game-from-github-contribution-grid"
description: "Generates a snake game from a github user contributions grid. Output the animation as gif or svg"
author: "platane"

runs:
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5,17 * * *'

  using: "docker"
  image: "docker://platane/snk:latest"

inputs:
  github_user_name:
    description: "adamwillisXanax"
    required: true
  gif_out_path:
    description: "path of the generated gif file. If left empty, the gif file will not be generated."
    required: false
    default: null
  svg_out_path:
    description: "path of the generated svg file. If left empty, the svg file will not be generated."
    required: false
    default: null

outputs:
  gif_out_path:
    description: "Assets/snake.gif"
  svg_out_path:
    description: "Assets/snake.svg"