# GitHub Action for generating a contribution graph with a snake eating your contributions.
name: Generate animation

on:
  # run automatically every 6 hours
  schedule:
    - cron: "0 */3 * * *" 

# This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

# run on every push on the master branch
  push:
    branches:
    - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk@master
        with:
          github_user_name: adamwillisXanax
          svg_out_path: dist/github-contribution-grid-snake.svg

      # push the content of <build_dir> to a branch
      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: 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